# Site
name: 'Siddharth'
description: 'Engineer. Computational Neuroscientist. Writer. Editor. Author of the book Founding Generations. Writes on International Affairs, History, and Politics.'
baseurl: ''
disqus: 'demowebsite'
email: 'sid.sapien@gmail.com'
mailchimp-list: 'https://feedburner.google.com/fb/a/mailverify?uri=ssiddharth/xkbQ&amp'

# for seo tagging
# Note: Apparently, Facebook and Twitter take some values from below but others like "image" and "description" from index.html
author: Siddharth
title: Siddharth's personal website.
url: https://ssiddharth.in
type: website
image: assets/images/my_avatar_post.jpg
twitter: 
  username: SidSapien
  card: summary_large_image
social:
  name: Siddharth
  links: 
    - https://www.facebook.com/siddharth.sapien
    - https://x.com/SidSapien
description: Engineer. Computational Neuroscientist. Writer. Editor. Author of the book Founding Generations. Writes on International Affairs, History, and Politics.
logo: assets/images/my_avatar_post.jpg
webmaster_verification:
  google: -Ae1kn9zfaHIXCLcWqbmY9sxnTJ_FTRDschRp6lD9x8



include: ["_pages"]
permalink: /:title/

favicon: 'assets/images/favicon.ico'

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

cloudinary:
  cloud_name: db8t6vlxo
  
authors:
    Siddharth:
      name:           Siddharth
      site:           https://ssiddharth.in
      avatar:         /assets/images/my_avatar_post.jpg
      bio:            "Hi, I am Siddharth!"
      email:          sid.sapien@gmail.com
      twitter:        https://x.com/SidSapien
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Siddharth
      avatar: /assets/images/my_avatar_post.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
